#!/usr/bin/env bash
#SBATCH --job-name=arc064v2
#SBATCH --output=%x-%j.out
#SBATCH --error=%x-%j.err
#SBATCH --partition=high
#SBATCH --time="14-00:00:00"
#SBATCH --mem-per-cpu=3GB
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=20
#SBATCH --mail-type="FAIL"
#SBATCH --mail-user="dominik.schrempf@gmail.com"

# Needs 149GB for 256 components with 4 rate categories.
./udm archaea_v2_linsi_bmge.fas UdmLclrHogenom.nex 064 20
