#!/usr/bin/env bash
#SBATCH --job-name=eukPmsfPrep256v2
#SBATCH --output=%x-%j.out
#SBATCH --error=%x-%j.err
#SBATCH --partition=high
#SBATCH --time="14-00:00:00"
#SBATCH --mem-per-cpu=7GB
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=20
#SBATCH --mail-type="FAIL"
#SBATCH --mail-user="dominik.schrempf@gmail.com"

# Needs 126GB for 256 components and 4 rate categories.
./pmsf-prep eukaryotes_v2_linsi_bmge.fas UdmLclrHogenom.nex 256 20 eukaryotes_v2_linsi_bmge.fas_LG.treefile
