# Renaming, 2 steps:

python Scripts/NEW_RenameLeavesAccordingToRefFile.py updated_concatenates/all_domains_concat.fas.treefileRN updated_concatenates/all_domains_concat.fas.treefile_renamed Archaea/Data/arc_metadata_r86.tsv

python Scripts/NEW_RenameLeavesAccordingToRefFile.py updated_concatenates/all_domains_concat.fas.treefileRN updated_concatenates/all_domains_concat.fas.treefile_renamed Archaea/Data/arc_metadata_r86.tsv

