#!/usr/bin/env bash

# Command arguments.
data_fn="$1"
dist_fn="$2"
n_comps="$3"
n_cpus="$4"
guide_tree_fn="$5"

udm_model="Poisson+UdmLclr${n_comps}+R4"

cmd_base=(iqtree)

cmd_opts=(-nt "$n_cpus"
          # -redo -mredo
          -s "$data_fn"
          -mdef "${dist_fn}"
	  -mwopt
	  -m "${udm_model}"
	  -ft "${guide_tree_fn}" 
          -pre "${data_fn}_${n_comps}_pmsf")

"${cmd_base[@]}" "${cmd_opts[@]}"
