#!/usr/bin/env bash
#SBATCH --job-name=all064
#SBATCH --output=%x-%j.out
#SBATCH --error=%x-%j.err
#SBATCH --partition=high
#SBATCH --time="14-00:00:00"
#SBATCH --mem-per-cpu=10GB
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=20
#SBATCH --mail-type="FAIL"
#SBATCH --mail-user="dominik.schrempf@gmail.com"

# Needs 90GB for 64 components with 4 rate categories.
./udm all_domains_concat.fas UdmLclrHogenom.nex 064 20
