#!/usr/bin/env bash
#SBATCH --job-name=euk256
#SBATCH --output=%x-%j.out
#SBATCH --error=%x-%j.err
#SBATCH --partition=high
#SBATCH --time="14-00:00:00"
#SBATCH --mem-per-cpu=12GB
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=20
#SBATCH --mail-type="FAIL"
#SBATCH --mail-user="dominik.schrempf@gmail.com"

# Needs 126GB for 256 components and 4 rate categories.
./udm euk_fams_linsi_bmge_concat.fas UdmLclrHogenom.nex 256 20
